name: Terraform apply

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        working-directory: ./s3


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id :  ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key : ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token :     ${{ secrets.SESSION_TOKEN }}
          aws-region : us-east-1

      - name: Deploy infrastructure with Terraform
        working-directory: ${{env.working-directory}}
        run: |
          terraform init
          terraform destroy -auto-approve
